[package]
name = "dino_game"
version = "0.1.0"
authors = ["Oleg Kosmakov <oleg.kosmakov@dataart.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
image = "0.23.8"
rand = "0.7.3"
rodio="0.11.0"
